"""Auto-generated runnable concatenation of Python blocks in
docs/configurations/ssa-baseline.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 2 runnable, 0 skipped
(doctest blocks are excluded because the doctest-docs tox env
already runs them via `pytest --doctest-glob`).
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
from laser.cholera.metapop.model import run_model

run_model(None, seed=20240930)


# ---- block 2 ----
from pathlib import Path

from laser.cholera.metapop.model import run_model

params_path = Path("src/laser/cholera/metapop/data/default_parameters.json")
run_model(params_path, seed=20240930)
