"""Auto-generated runnable concatenation of Python blocks in
docs/configurations/single-location.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 1 runnable, 0 skipped
(`runnable` includes plain `python` blocks AND `pycon` / `>>>` doctest
blocks with prompts stripped; the latter also run independently via
the `doctest-docs` tox env's `pytest --doctest-glob`. `skipped` are
the `<!-- doc-test:skip -->`-tagged blocks that were dropped.)
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
from pathlib import Path

from laser.cholera.metapop.model import run_model

params_path = Path("docs/configurations/code/single-location.json")
run_model(params_path, seed=20240930)
