"""Auto-generated runnable concatenation of Python blocks in
docs/how-to/enable-seasonality.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 1 runnable, 5 skipped
(doctest blocks are excluded because the doctest-docs tox env
already runs them via `pytest --doctest-glob`).
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
import numpy as np
from laser.cholera.metapop.params import get_parameters

# Start from the bundled defaults to discover npatches.
import numpy as np

defaults = get_parameters(None, do_validation=False)
npatches = len(defaults.location_name)

mods = {
    "p": 365,
    "a_1_j": np.full(npatches, 0.30, dtype=np.float32),
    "b_1_j": np.full(npatches, 0.10, dtype=np.float32),
    "a_2_j": np.full(npatches, 0.10, dtype=np.float32),
    "b_2_j": np.full(npatches, 0.05, dtype=np.float32),
}
params = get_parameters(mods=mods)

t = np.arange(365)
j = 0
seasonal = (1
            + params.a_1_j[j] * np.cos(2 * np.pi * t / params.p)
            + params.b_1_j[j] * np.sin(2 * np.pi * t / params.p)
            + params.a_2_j[j] * np.cos(4 * np.pi * t / params.p)
            + params.b_2_j[j] * np.sin(4 * np.pi * t / params.p))
