"""Auto-generated runnable concatenation of Python blocks in
docs/how-to/configure-mobility.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 1 runnable, 5 skipped
(doctest blocks are excluded because the doctest-docs tox env
already runs them via `pytest --doctest-glob`).
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
import numpy as np

from laser.cholera.metapop.model import run_model
from laser.cholera.metapop.params import get_parameters

# Start from the bundled defaults to discover npatches; the gravity-model
# `pi_ij` is a derived `(npatches, npatches)` matrix on `model.patches`.
defaults = get_parameters(None, do_validation=False)
npatches = len(defaults.location_name)

mods = {
    "tau_i": np.full(npatches, 0.01, dtype=np.float32),
    "mobility_omega": 1.0,
    "mobility_gamma": 1.5,
}
model = run_model(None, **mods)

pi_ij = model.patches.pi_ij
assert pi_ij.shape == (npatches, npatches)
assert np.allclose(pi_ij.sum(axis=1), 1.0, atol=1e-4)
