"""Auto-generated runnable concatenation of Python blocks in
docs/how-to/calibrate-and-score.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 1 runnable, 6 skipped
(doctest blocks are excluded because the doctest-docs tox env
already runs them via `pytest --doctest-glob`).
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
import numpy as np
from laser.cholera.metapop.model import run_model
from laser.cholera.metapop.params import get_parameters

params = get_parameters().to_dict()

params["calc_likelihood"] = True
params["reported_cases"] = np.array(
    [[5, 8, 12, 7], [3, 6, np.nan, 4]], dtype="float32"
).tolist()
params["reported_deaths"] = np.array(
    [[0, 1, 1, 0], [0, 0, 1, 0]], dtype="float32"
).tolist()
params["weight_peak_timing"] = 0.25
params["weight_cumulative_total"] = 0.25
params["epidemic_peaks"] = [
    {"iso_code": "MOZ", "peak_date": "2024-03-15"},
    {"iso_code": "MWI", "peak_date": "2024-04-02"},
]

model = run_model(params)
print(model.log_likelihood)
