"""Auto-generated runnable concatenation of Python blocks in
docs/how-to/override-parameters.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 1 runnable, 2 skipped
(`runnable` includes plain `python` blocks AND `pycon` / `>>>` doctest
blocks with prompts stripped; the latter also run independently via
the `doctest-docs` tox env's `pytest --doctest-glob`. `skipped` are
the `<!-- doc-test:skip -->`-tagged blocks that were dropped.)
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
from laser.cholera.metapop.model import run_model

# Two scalar overrides applied at load time; `run_model` forwards `**kwargs`
# to `get_parameters` as `mods`. For an array-typed field (e.g.
# `S_j_initial`) wrap the value with `numpy.array(..., dtype=...)` per the
# warning above — otherwise the list survives untyped into the validator.
model = run_model(None, seed=20240930, phi_1=0.65)
