"""Auto-generated runnable concatenation of Python blocks in
docs/how-to/enable-vaccination.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 1 runnable, 6 skipped
(`runnable` includes plain `python` blocks AND `pycon` / `>>>` doctest
blocks with prompts stripped; the latter also run independently via
the `doctest-docs` tox env's `pytest --doctest-glob`. `skipped` are
the `<!-- doc-test:skip -->`-tagged blocks that were dropped.)
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
import numpy as np

from laser.cholera.metapop.model import run_model
from laser.cholera.metapop.params import get_parameters

# Use `run_model` for the full default component pipeline; it forwards kwargs
# as `mods` to `get_parameters`, so any per-tick array we build here lands on
# the params set before validation runs.
defaults = get_parameters(None, do_validation=False)
nticks = defaults.nticks
npatches = len(defaults.location_name)

nu_1_jt = np.zeros((nticks, npatches), dtype=np.float32)
nu_1_jt[30:, :] = 50.0

nu_2_jt = np.zeros((nticks, npatches), dtype=np.float32)
nu_2_jt[60:, :] = 50.0

model = run_model(
    None,
    nu_1_jt=nu_1_jt,
    nu_2_jt=nu_2_jt,
    phi_1=0.75,
    phi_2=0.85,
    omega_1=float(np.log(2) / (5 * 365.25)),
    omega_2=float(np.log(2) / (5 * 365.25)),
    nu_jt_sources=["S", "E", "Isym", "Iasym", "R"],
)
