"""Auto-generated runnable concatenation of Python blocks in
docs/tutorials/first-run.md.

Regenerated by tests/docs/extract_doc_blocks.py — do not hand-edit.

Blocks extracted: 4 runnable, 0 skipped
(doctest blocks are excluded because the doctest-docs tox env
already runs them via `pytest --doctest-glob`).
"""

from __future__ import annotations

# Force a non-interactive matplotlib backend BEFORE any `import
# matplotlib` runs further down. `plt.show()` becomes a no-op and
# no GUI window is opened — needed because some doc blocks render
# trajectories with `matplotlib.pyplot`. `setdefault` so a caller
# who explicitly wants an interactive run can pass MPLBACKEND=...
# in their shell env.
import os

os.environ.setdefault("MPLBACKEND", "Agg")


# ---- block 1 ----
from laser.cholera.metapop.model import run_model

model = run_model(None)


# ---- block 2 ----
S = model.people.S
print(S.shape)
print(S[0])    # initial S per patch (seeded from params.S_j_initial)
print(S[-1])   # S at the final tick


# ---- block 3 ----
incidence = model.patches.incidence
reported_cases = model.patches.reported_cases
print(incidence.shape, reported_cases.shape)
print(reported_cases[-1])  # final-tick reported cases per patch


# ---- block 4 ----
import matplotlib.pyplot as plt

infectious_total = model.people.Isym.sum(axis=1) + model.people.Iasym.sum(axis=1)
plt.plot(infectious_total)
plt.xlabel("Tick (day)")
plt.ylabel("Total infectious (Isym + Iasym)")
plt.show()
