name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Bump type (major, minor, patch):"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: "Dry run (true/false):"
        required: false
        default: "false"
        type: choice
        options:
          - false
          - true

jobs:
  approve:
    name: Approve Bump
    environment: restricted
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Requesting approval for ${{ github.event.inputs.version_type }} version bump"

  test:
    name: Run Tests on ${{ matrix.os }}
    needs: approve
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Install UV
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Install Package and Dependencies
        run: uv pip install -e ".[dev]"

      - name: Run Tests
        run: pytest

  bump-and-build:
    name: Bump Version and Build Package
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Print Inputs
        run: |
          echo "Version type: ${{ github.event.inputs.version_type }}"
          echo "Dry run: ${{ github.event.inputs.dry_run }}"

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Install UV
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Bump Version
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          DRY_FLAG="${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}"  # convert true/false to --dry-run or empty string
          uvx --python 3.12 bump-my-version bump ${{ github.event.inputs.version_type }} $DRY_FLAG

      - name: Push Changes and Tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main
          git push origin v$(bump-my-version show current_version)

      - name: Build Package
        run: uv build

      - name: Upload Artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=v$(bump-my-version show current_version)
          gh release create "$tag_name" dist/* --title "$tag_name" --notes "Automated release for $tag_name" || \
          gh release upload "$tag_name" dist/*
